// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SalesReturnsSystem.Entities;

[Table("Job")]
public partial class Job
{
    [Key]
    public int JobID { get; set; }

    public int? CustomerVehicleID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime JobDateIn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? JobDateStarted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? JobDateDone { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? JobDateOut { get; set; }

    [Required]
    [StringLength(450)]
    public string EmployeeID { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal ShopRate { get; set; }

    [Required]
    [StringLength(13)]
    public string VehicleIdentification { get; set; }

    public int? CouponID { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("CouponID")]
    [InverseProperty("Jobs")]
    public virtual Coupon Coupon { get; set; }

    [ForeignKey("CustomerVehicleID")]
    [InverseProperty("Jobs")]
    public virtual CustomerVehicle CustomerVehicle { get; set; }

    [InverseProperty("Job")]
    public virtual ICollection<JobDetail> JobDetails { get; set; } = new List<JobDetail>();

    [InverseProperty("Job")]
    public virtual ICollection<JobPart> JobParts { get; set; } = new List<JobPart>();
}