// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SalesReturnsSystem.Entities;

[Table("Sale")]
public partial class Sale
{
    [Key]
    public int SaleID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime SaleDate { get; set; }

    public int CustomerID { get; set; }

    [Required]
    [StringLength(450)]
    public string EmployeeID { get; set; }

    [Column(TypeName = "money")]
    public decimal TaxAmount { get; set; }

    [Column(TypeName = "money")]
    public decimal SubTotal { get; set; }

    public int? CouponID { get; set; }

    [Required]
    [StringLength(1)]
    public string PaymentType { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("CouponID")]
    [InverseProperty("Sales")]
    public virtual Coupon Coupon { get; set; }

    [ForeignKey("CustomerID")]
    [InverseProperty("Sales")]
    public virtual Customer Customer { get; set; }

    [InverseProperty("Sale")]
    public virtual ICollection<SaleDetail> SaleDetails { get; set; } = new List<SaleDetail>();

    [InverseProperty("Sale")]
    public virtual ICollection<SaleRefund> SaleRefunds { get; set; } = new List<SaleRefund>();
}