@base_address = http://localhost:3000/api/people

POST {{base_address}}
# {{Accept: application/json}}
Content-Type: application/json

{
    "firstName" : "Sun",
    "lastName" : "T"
}

###
GET  {{base_address}}

###
GET  {{base_address}}/1

###
PUT  {{base_address}}/3
# {{Accept: application/json}}
Content-Type: application/json

{
    "id":3,
    "firstName" : "Something",
    "lastName" : "T"
}


###
DELETE {{base_address}}/3