// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExampleMudSystem.Entities;

[Keyless]
[Table("UnitTest")]
internal partial class UnitTest
{
    public int UnitTestID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string TableName { get; set; }

    public int ReferenceID { get; set; }
}