// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ReceivingSystem.Entities;

[Table("JobDetail")]
public partial class JobDetail
{
    [Key]
    public int JobDetailID { get; set; }

    public int JobID { get; set; }

    [Required]
    [StringLength(100)]
    public string Description { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal JobHours { get; set; }

    public string Comments { get; set; }

    public int? CouponID { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string StatusCode { get; set; }

    [StringLength(450)]
    public string EmployeeID { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("CouponID")]
    [InverseProperty("JobDetails")]
    public virtual Coupon Coupon { get; set; }

    [ForeignKey("JobID")]
    [InverseProperty("JobDetails")]
    public virtual Job Job { get; set; }
}